### ISSUE TITLE
Question Regarding the RAP Paper

### ISSUE THREAD

**Issue by janghobaik** [Ash-Zheng/RAP-artifacts#1]
As mentioned in the RAP paper, there are not many papers focused on preprocessing in training systems, which has piqued my interest in researching this area.

I understand that DLRM preprocessing can be performed using either Numpy-based methods or NVTabular. To use NVTabular, I’m aware that raw data needs to be stored in the Parquet file format.

In the RAP paper, the baseline seemed to be Torcharrow (PyArrow for PyTorch). Do you consider NVTabular as a baseline as well?

**Comment by Ash-Zheng** [comment]
Hi @janghobaek2125, the reason we chose to use TorchArrow and did not include NVTabular as a baseline is that TorchArrow offers specific input preprocessing operations, such as [SigridHash](https://github.com/pytorch/torcharrow/blob/release/0.1.0/csrc/velox/functions/rec/sigrid_hash.h), which are utilized in production DLRM model training.

**Comment by janghobaik** [comment]
Hello, I would like to confirm my understanding of why TorchArrow is used instead of NVTabular. As I understand, TorchArrow utilizes UDFs like SigridHash to efficiently preprocess dynamic data in recommendation systems. It also helps reduce the complexity of reprocessing when adjusting embedding table sizes and has strong support for handling Parquet-format data.

While NVTabular is optimized for large-scale data preprocessing, TorchArrow seems tailored for specialized workflows like Meta's RecSys. Is this the reason TorchArrow was chosen for TorchRec-based training loops? I would appreciate your confirmation. 

Thank you.

**Comment by Ash-Zheng** [comment]
> Hello, I would like to confirm my understanding of why TorchArrow is used instead of NVTabular. As I understand, TorchArrow utilizes UDFs like SigridHash to efficiently preprocess dynamic data in recommendation systems. It also helps reduce the complexity of reprocessing when adjusting embedding table sizes and has strong support for handling Parquet-format data.
> 
> While NVTabular is optimized for large-scale data preprocessing, TorchArrow seems tailored for specialized workflows like Meta's RecSys. Is this the reason TorchArrow was chosen for TorchRec-based training loops? I would appreciate your confirmation.
> 
> Thank you.

Yes, this is the main reason that we choose TorchArrow rather than NVTabular.
